title: Jose Carreras # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Here's a little section about me, you can find more about me and what I do. Currently I'm finishing my Higher National Diploma in App development. I'm also working in my own Unity projects and thats the main thing I'll be uploading here. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/jose-carreras-morala/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
